name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Blender
      run: |
        sudo apt-get update
        sudo apt-get install -y blender

    - name: Execute .blend file
      run: |
        blender -b path_to_your_file.blend -P path_to_your_script.py
