name: Run Blender on Windows

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  run-blender-job:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify your Python version

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; `
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Blender
      run: |
        choco install blender -y

    - name: Find Blender Path
      run: |
        $blenderPath = (Get-Command blender | Select-Object -ExpandProperty Source)
        Write-Output "Blender Path: $blenderPath"

    - name: Run btest.py
      run: |
        python btest.py

